[tool.poetry]
name = "py-now-playing"
version = "0.2.0-rc1"
description = "A Python Library to get the currently playing media"
authors = ["ABUCKY0 <81783950+ABUCKY0@users.noreply.github.com>"]
readme = "README.md"
homepage = "https://py-now-playing.readthedocs.io/en/rewrite-2/README.html"
repository = "https://github.com/abucky0/py-now-playing"
license = "GNU General Public License v3 (GPLv3)"

[tool.poetry.dependencies]
python = ">=3.11,<3.14"
pillow = ">=10.1,<13.0"
winrt-Windows-Media = "^2.3.0"
winrt-windows-media-control = "^2.3.0"
winrt-windows-storage = "^2.3.0"
winrt-windows-storage-streams = "^2.3.0"
winrt-windows-foundation = "^2.3.0"
winrt-windows-foundation-collections = "^2.3.0"

[tool.poetry.group.dev.dependencies]
asynctest = "^0.13.0"
pypresence = {url = "https://github.com/ghostselfbot/pypresence/archive/a9fd62dc9adb025acd2218c4e1e78ecbf2c0ca5d.zip"} # https://github.com/qwertyquerty/pypresence/archive/f856ccaaeb2321f64f9692b75dc3ceda5c927f42.zip
requests = "^2.32.3"
flet = "^0.25.2"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"