[tool.poetry]
name = "py-now-playing"
version = "0.1.0"
description = ""
authors = ["ABUCKY0 <81783950+ABUCKY0@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
